version: '3'
services:
  nginx:
    build: ./frontend
    image: 'sensor-nginx:latest'
    restart: always
    container_name: frontend
    ports:
      - 80:80
    networks:
      compose:
        ipv4_address: 10.20.30.6
  api:
    build: ./backend
    image: 'sensor-api:latest'
    restart: always
    container_name: backend
    ports:
      - 8080:8080
    networks:
      compose:
        ipv4_address: 10.20.30.7
    environment:
      spring.profiles.active: 'prod'
  coap-server:
    image: 'sensor-coap:latest'
    restart: always
    container_name: coap-server
    ports:
      - 5683:5683
    networks:
      compose:
        ipv4_address: 10.20.30.8
    environment:
      spring.profiles.active: 'prod'
#  db:
#    image: 'mysql:latest'
#    restart: always
#    container_name: mysql
#    ports:
#      - 3306:3306
#    networks:
#      compose:
#        ipv4_address: 10.20.30.9
#    environment:
#      MYSQL_ROOT_PASSWORD: sensor12345
#      MYSQL_DATABASE: sensor
#      MYSQL_USER: sensor
#      MYSQL_PASSWORD: sensor12345
#    volumes:
#      - data:/var/lib/mysql/
#volumes:
#    data:
#      external: false
networks:
  compose:
    driver: bridge
    external: true
    ipam:
      driver: default
      config:  
        - subnet: 10.20.30.0/24
