# Logger activation
logging:
  level:
    edu.fra.uas.coap.server: debug
# Mysql connection:
spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.80.2.239:3306/sensor?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: sensor
    password: sensor12345
  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
coap:
  server: 127.0.0.1